PetBuffs.Pets = {
  {
    id = 1,
    name = 'Wolf',
    icon = 'Ability_Hunter_Pet_Wolf',
    model = 26331,
  },
  {
    id = 2,
    name = 'Cat',
    icon = 'Ability_Hunter_Pet_Cat',
    model = 39579,
  },
  {
    id = 3,
    name = 'Spider',
    icon = 'Ability_Hunter_Pet_Spider',
    model = 26331,
  },
  {
    id = 4,
    name = 'Bear',
    icon = 'Ability_Hunter_Pet_Bear',
    model = 26331,
  },
  {
    id = 5,
    name = 'Boar',
    icon = 'Ability_Hunter_Pet_Boar',
    model = 26331,
  },
  {
    id = 6,
    name = 'Crocolisk',
    icon = 'Ability_Hunter_Pet_Crocolisk',
    model = 26331,
  },
  {
    id = 7,
    name = 'Carrion Bird',
    icon = 'Ability_Hunter_Pet_Vulture',
    model = 26331,
  },
  {
    id = 8,
    name = 'Crab',
    icon = 'Ability_Hunter_Pet_Crab',
    model = 26331,
  },
  {
    id = 9,
    name = 'Gorilla',
    icon = 'Ability_Hunter_Pet_Gorilla',
    model = 26331,
  },
  {
    id = 11,
    name = 'Raptor',
    icon = 'Ability_Hunter_Pet_Raptor',
    model = 26331,
  },
  {
    id = 12,
    name = 'Tallstrider',
    icon = 'Ability_Hunter_Pet_TallStrider',
    model = 26331,
  },
  {
    id = 20,
    name = 'Scorpid',
    icon = 'Ability_Hunter_Pet_Scorpid',
    model = 26331,
  },
  {
    id = 21,
    name = 'Turtle',
    icon = 'Ability_Hunter_Pet_Turtle',
    model = 26331,
  },
  {
    id = 24,
    name = 'Bat',
    icon = 'Ability_Hunter_Pet_Bat',
    model = 26331,
  },
  {
    id = 25,
    name = 'Hyena',
    icon = 'Ability_Hunter_Pet_Hyena',
    model = 26331,
  },
  {
    id = 26,
    name = 'Bird of Prey',
    icon = 'Ability_Hunter_Pet_Owl',
    model = 26331,
  },
  {
    id = 27,
    name = 'Wind Serpent',
    icon = 'Ability_Hunter_Pet_WindSerpent',
    model = 2705,
  },
  {
    id = 30,
    name = 'Dragonhawk',
    icon = 'Ability_Hunter_Pet_DragonHawk',
    model = 26331,
  },
  {
    id = 31,
    name = 'Ravager',
    icon = 'Ability_Hunter_Pet_Ravager',
    model = 26331,
  },
  {
    id = 32,
    name = 'Warp Stalker',
    icon = 'Ability_Hunter_Pet_WarpStalker',
    model = 26331,
  },
  {
    id = 33,
    name = 'Sporebat',
    icon = 'Ability_Hunter_Pet_Sporebat',
    model = 26331,
  },
  {
    id = 34,
    name = 'Nether Ray',
    icon = 'Ability_Hunter_Pet_NetherRay',
    model = 26331,
  },
  {
    id = 35,
    name = 'Serpent',
    icon = 'Spell_Nature_GuardianWard',
    model = 26331,
  },
  {
    id = 37,
    name = 'Moth',
    icon = 'Ability_Hunter_Pet_Moth',
    model = 26331,
  },
  {
    id = 38,
    name = 'Chimaera',
    icon = 'Ability_Hunter_Pet_Chimera',
    model = 26331,
  },
  {
    id = 39,
    name = 'Devilsaur',
    icon = 'Ability_Hunter_Pet_Devilsaur',
    model = 26331,
  },
  {
    id = 41,
    name = 'Silithid',
    icon = 'Ability_Hunter_Pet_Silithid',
    model = 26331,
  },
  {
    id = 42,
    name = 'Worm',
    icon = 'Ability_Hunter_Pet_Worm',
    model = 26331,
  },
  {
    id = 43,
    name = 'Clefthoof',
    icon = 'inv_clefthoofdraenormount_blue',
    model = 26331,
  },
  {
    id = 44,
    name = 'Wasp',
    icon = 'Ability_Hunter_Pet_Wasp',
    model = 26331,
  },
  {
    id = 45,
    name = 'Core Hound',
    icon = 'Ability_Hunter_Pet_CoreHound',
    model = 26331,
  },
  {
    id = 46,
    name = 'Spirit Beast',
    icon = 'Ability_Druid_PrimalPrecision',
    model = 26331,
  },
  {
    id = 50,
    name = 'Fox',
    icon = 'ability_hunter_aspectofthefox',
    model = 26331,
  },
  {
    id = 51,
    name = 'Monkey',
    icon = 'inv_pet_monkey',
    model = 26331,
  },
  {
    id = 52,
    name = 'Dog',
    icon = 'inv_pet_mastiff',
    model = 26331,
  },
  {
    id = 53,
    name = 'Beetle',
    icon = 'inv_misc_ahnqirajtrinket_01',
    model = 26331,
  },
  {
    id = 55,
    name = 'Shale Spider',
    icon = 'inv_pet_ shalespider',
    model = 26331,
  },
  {
    id = 68,
    name = 'Hydra',
    icon = 'trade_archaeology_whitehydrafigurine',
    model = 26331,
  },
  {
    id = 125,
    name = 'Crane',
    icon = 'inv_pet_crane',
    model = 26331,
  },
  {
    id = 126,
    name = 'Water Strider',
    icon = 'inv_pet_waterstrider',
    model = 26331,
  },
  {
    id = 127,
    name = 'Porcupine',
    icon = 'inv_pet_porcupine',
    model = 26331,
  },
  {
    id = 128,
    name = 'Quilen',
    icon = 'achievement_moguraid_01',
    model = 26331,
  },
  {
    id = 129,
    name = 'Goat',
    icon = 'inv_pet_ goat',
    model = 26331,
  },
  {
    id = 130,
    name = 'Basilisk',
    icon = 'inv_pet_ basilisk',
    model = 26331,
  },
  {
    id = 138,
    name = 'Direhorn',
    icon = 'inv_pet_direhorn',
    model = 26331,
  },
  {
    id = 149,
    name = 'Rylak',
    icon = 'ability_mount_ironchimera',
    model = 26331,
  },
  {
    id = 150,
    name = 'Riverbeast',
    icon = 'inv_hippo_green',
    model = 26331,
  },
  {
    id = 151,
    name = 'Stag',
    icon = 'inv_talbukdraenor_white',
    model = 26331,
  }
}
